# Generated by Django 2.2.7 on 2019-12-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новый'), (2, 'В работе'), (3, 'Выполнено')], default=1),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qrzone',
            name='is_active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
